### PR TITLE
Try to fix missing post types again

### PR DESCRIPTION
**Pull request by kurtw**
Sets menu position to 100 for it to be below the second visual separator, and more importantly below every other option. [Here's the doc explaining the menu position parameter.](http://codex.wordpress.org/Function_Reference/register_post_type)

### CODE REVIEW

**Comment by Scotchester** [comment]
@kurtw Let's get this current with the master branch. I think it's probably valuable to go ahead and merge it so that it's easier to work with the menu editor.

**Comment by cfarm** [comment]
Agree with @Scotchester! We just ran into this issue with OAH custom post type missing.

**Comment by kurtw** [comment]
Updated.

**Comment by Scotchester** [comment]
Thanks!

**Comment by Scotchester** [comment]
Please tag and release.

**Pull request merged**
