### PR TITLE
Fix stupid tests

### PR DESCRIPTION
**Pull request by kurtw**
Go into UB and run `phpunit` or `./vendor/bin/phpunit` in the cms-toolkit repo

@dpford

### CODE REVIEW

**Comment by dpford** [comment]
simply

**Comment by jimmynotjim** [comment]
Tests run and pass :+1:

**Comment by Scotchester** [comment]
Why was this closed?

**Comment by kurtw** [comment]
Should've put in a description. I didn't want a version change on a test fix so I rebased the tagged commit on top of the commit that fixes the tests, hence not merging here.

**Comment by kurtw** [comment]
Now patiently waiting for you to yell at me. :fearful:

**Comment by Scotchester** [comment]
Gotcha. I'm fine with that. Just wanted an explanation for why this was closed :)

**Comment by kurtw** [comment]
:+1:

**Pull request closed without merging**
