### PR TITLE
Fix failing tests

### PR DESCRIPTION
**Pull request by kurtw**
This pull request fixes failing tests on build and removes an erroneous function that snuck into the code.

@willbarton

### CODE REVIEW

**Comment by willbarton** [comment]
:8ball: ... Tests pass here.

**Comment by willbarton** [comment]
Can you bump the version in `cms-toolkit.php`?

**Comment by kurtw** [comment]
I was going to do it in another PR but I should do it in this one.

**Comment by kurtw** [comment]
Since this is part of a more important addition to functionality, I figured this deserved a +.1 in upgrade.

**Comment by willbarton** [comment]
selfie-0

**Pull request merged**
