### PR TITLE
Remove browser validation from the url field

### PR DESCRIPTION
**Pull request by kurtw**
### Why do we need this
Content folks would like to be able to add relative urls in the url field so they won't have to update every post after RAMPing.

#### And they can't do it because...
The browser is doing it's own validation. Any data entered into a url type input field must conform to the validations' standards. It does not. 

#### Okay so how did we fix it?
~~We can specify an attribute in the form tag named `novalidate` documented [here](http://www.w3schools.com/tags/att_input_formnovalidate.asp).~~ We change the input type from `url` to `text` to workaround the validation.

### Side effects?
Yes. We are relying on this kind of validation for making sure the entered data is a valid url. ~~stopping the submission of data without required fields. This would allow fields that we've specified as required to be submitted _without data_. Though, we only have a couple fields at most that use this, AND~~ we should be doing our own validation anyway, not relying on the browsers. I smell another PR coming....

Anyway, if you've read this far then congratulations! You've spent more time reading about this than the time it would take to actually perform the review. Sorry for wasting your time, and thanks for reviewing!

@dpford @willbarton @Scotchester

### CODE REVIEW

**Comment by Scotchester** [comment]
:-1: 

I don't think we should do this. It seems like an antipattern, for the reasons you've given in the Side Effects section. It could also mess with some default WordPress form validation. IMO, the better stopgap solution until we get our own validation in there is to simply change the field type to `text`.

**Comment by kurtw** [comment]
@Scotchester  should we add `novalidate` after we've added our own validation then?

**Comment by Scotchester** [comment]
I don't think so, for the same reason. It could still interfere with any native validation that WordPress itself does by default.

**Comment by kurtw** [comment]
Updated.

**Comment by Scotchester** [comment]
:+1: now. I'll give some others a chance to comment before merging.

**Comment by Scotchester** [comment]
Time's up!

**Pull request merged**
